# 내 의견함(시민) + 운영팀 의견함 화면 테스트 — 가짜 DB(feedback/fake-db.js) 미리보기 사용
# 실행: python social_world/feedback/tests/ui_test.py   (Playwright 필요)
import pathlib, re, sys
from playwright.sync_api import sync_playwright

HERE = pathlib.Path(__file__).resolve().parent
SW = HERE.parent.parent
citizen_url = SW.joinpath('feedback', 'feedback-preview.html').as_uri()
admin_url = SW.joinpath('admin', 'admin-preview.html').as_uri()
fails = []
def check(cond, name):
    print(('PASS  ' if cond else 'FAIL  ') + name)
    if not cond: fails.append(name)

with sync_playwright() as p:
    b = p.chromium.launch()
    for w, h, tag in [(1100, 820, 'desktop'), (390, 780, 'mobile')]:
        # ---------------- 시민: 내 의견함
        pg = b.new_page(viewport={'width': w, 'height': h})
        pg.goto(citizen_url)
        pg.wait_for_selector('.fb-item')
        check(pg.locator('.fb-item').count() == 2, f'[{tag}] 내 의견 2개만(남의 의견 없음)')
        check(pg.locator('#badge').inner_text() == '새 답 1', f'[{tag}] 안 읽은 답 배지 1')
        first = pg.locator('.fb-item', has_text='분수')
        check(first.locator('.fb-new').count() == 1, f'[{tag}] 새 답 표시')
        haru = pg.locator('.fb-item', has_text='하루에게')
        check('강남구 교통비' in haru.inner_text(), f'[{tag}] 하루 창구 의견엔 정책 이름')
        first.locator('.fb-head').click()
        check(first.locator('.fb-head').get_attribute('aria-expanded') == 'true', f'[{tag}] 펼침')
        check('이장이 운영팀 답을 전해 왔어요' in first.inner_text(), f'[{tag}] 이장이 전달')
        check('운영팀 · 사람이 직접 쓴 답' in first.locator('.fb-bubble.staff').inner_text(), f'[{tag}] 답장은 사람(운영팀)이 쓴 것으로 표시')
        pg.wait_for_function('document.getElementById("badge").hidden')
        check(first.locator('.fb-new').count() == 0, f'[{tag}] 열면 읽음 처리, 배지 사라짐')
        first.locator('textarea').fill('휴대폰이에요. 010-1234-5678')
        first.get_by_role('button', name='답장 보내기').click()
        pg.wait_for_function('document.querySelectorAll(".fb-item .fb-bubble.me").length >= 2')
        item = pg.locator('.fb-item', has_text='분수')
        check(pg.locator('.fb-item').first.get_attribute('data-id') == '1' and '[전화번호]' in item.inner_text(), f'[{tag}] 답장 저장(전화번호 가림), 맨 위로, 대화 유지')
        item.locator('textarea').fill('그냥 사라지고 싶어요')
        item.get_by_role('button', name='답장 보내기').click()
        pg.wait_for_selector('.fb-crisis')
        check('109' in pg.locator('.fb-crisis').inner_text(), f'[{tag}] 답장 위기 표현 → 위기 안내')
        # 지우기 — 두 번 눌러야
        pg.click('#show-inbox')
        pg.wait_for_selector('.fb-item')
        n0 = pg.locator('.fb-item').count()
        last = pg.locator('.fb-item').nth(n0 - 1)
        last.locator('.fb-head').click()
        dele = last.get_by_role('button', name='이 의견 지우기')
        dele.click()
        check(pg.locator('.fb-item').count() == n0 and '정말 지울까요' in last.inner_text(), f'[{tag}] 한 번 누르면 확인만')
        last.get_by_role('button', name=re.compile('정말 지울까요')).click()
        pg.wait_for_function(f'document.querySelectorAll(".fb-item").length === {n0 - 1}')
        check(True, f'[{tag}] 두 번 누르면 지움')

        # 새 의견
        pg.click('#show-compose')
        pg.get_by_role('button', name='보내기').click()
        check('종류를 하나' in pg.locator('.fb-msg').inner_text(), f'[{tag}] 종류 없이 못 보냄')
        pg.get_by_role('button', name='불편해요').click()
        check(pg.get_by_role('button', name='불편해요').get_attribute('aria-pressed') == 'true', f'[{tag}] 종류 선택 표시')
        pg.get_by_role('button', name='보내기').click()
        check('한 줄만' in pg.locator('.fb-msg').inner_text(), f'[{tag}] 빈 글 못 보냄')
        pg.locator('textarea').fill('공원 가는 길이 헷갈려요')
        pg.get_by_role('button', name='보내기').click()
        pg.wait_for_function('document.querySelector(".fb").innerText.indexOf("내 의견함") >= 0')
        check('운영팀에 전할게요' in pg.locator('.fb').inner_text(), f'[{tag}] 저장 안내')
        sent = 1
        while sent < 6:
            pg.click('#show-compose'); pg.get_by_role('button', name='불편해요').click()
            pg.locator('textarea').fill(f'의견 {sent}'); pg.get_by_role('button', name='보내기').click()
            pg.wait_for_function('!document.querySelector(".fb-btn") || !document.querySelector(".fb-btn").disabled || document.querySelector(".fb-msg").innerText.length > 0')
            pg.wait_for_timeout(200)
            sent += 1
        check('내일 다시' in pg.locator('.fb').inner_text(), f'[{tag}] 하루 5건 넘으면 제한 안내')
        pg.click('#show-compose'); pg.get_by_role('button', name='오류가 있어요').click()
        pg.locator('textarea').fill('요즘 죽고 싶어요'); pg.get_by_role('button', name='보내기').click()
        pg.wait_for_selector('.fb-crisis')
        check('1577-0199' in pg.locator('.fb-crisis').inner_text(), f'[{tag}] 새 의견 위기 표현 → 위기 안내(저장 안 함)')
        pg.click('#show-missing')
        pg.wait_for_function('document.querySelector(".fb").innerText.indexOf("불러오는 중") < 0')
        check('불러오지 못했어요' in pg.locator('.fb').inner_text(), f'[{tag}] 07 적용 전 안내')
        pg.click('#show-fail'); pg.get_by_role('button', name='불편해요').click()
        pg.locator('textarea').fill('x'); pg.get_by_role('button', name='보내기').click()
        pg.wait_for_function('document.querySelector(".fb-msg").innerText.length > 0')
        check('받을 수 없어요' in pg.locator('.fb-msg').inner_text(), f'[{tag}] 네트워크 실패 안내')
        check(pg.evaluate('document.documentElement.scrollWidth <= innerWidth'), f'[{tag}] 시민 화면 가로 넘침 없음')
        pg.click('#show-inbox'); pg.wait_for_selector('.fb-item'); pg.locator('.fb-item').first.locator('.fb-head').click()
        pg.screenshot(path=str(HERE / f'shot_inbox_{tag}.png'), full_page=True)
        pg.close()

        # ---------------- 운영팀
        pg = b.new_page(viewport={'width': w, 'height': h})
        pg.goto(admin_url)
        pg.wait_for_selector('.fa-login')
        check(pg.evaluate('document.activeElement.id') == 'fa-email', f'[{tag}] 운영팀 로그인 화면')
        pg.fill('#fa-email', 'staff@eum.test'); pg.fill('#fa-pw', 'wrong'); pg.get_by_role('button', name='로그인').click()
        pg.wait_for_function('document.querySelector(".fa-msg").innerText.length > 0')
        check('확인해 주세요' in pg.locator('.fa-msg').inner_text(), f'[{tag}] 비밀번호 틀림')
        pg.fill('#fa-email', 'citizen@eum.test'); pg.fill('#fa-pw', 'test1234'); pg.get_by_role('button', name='로그인').click()
        pg.wait_for_function('document.querySelector(".fa-msg") && document.querySelector(".fa-msg").innerText.indexOf("명단") >= 0')
        check(True, f'[{tag}] 명단에 없는 계정은 거절')
        pg.fill('#fa-email', 'staff@eum.test'); pg.fill('#fa-pw', 'test1234'); pg.get_by_role('button', name='로그인').click()
        pg.wait_for_selector('.fa-tabs')
        tabs = pg.locator('.fa-tab')
        check(tabs.nth(0).inner_text().replace('\n', '') == '답 필요1', f'[{tag}] 답 필요 1건(운영팀이 마지막에 쓴 건 제외)')
        check(pg.locator('.fa-item').count() == 1 and '주민 #7F3A' in pg.locator('.fa-item').first.inner_text(), f'[{tag}] 가명 번호로 표시')
        check('@' not in pg.locator('.fa-list').inner_text(), f'[{tag}] 목록에 계정 정보 없음')
        pg.locator('.fa-item').first.click()
        th = pg.locator('.fa-thread')
        check('하루' in th.inner_text() and '강남구 교통비 지원사업' in th.inner_text(), f'[{tag}] 하루 창구 · 정책 이름')
        check(th.locator('a[href*="bokjiro.go.kr"][href*="WLF00006014"]').count() == 1, f'[{tag}] 정책 복지로 링크')
        check(pg.evaluate('document.activeElement.id') == 'fa-reply', f'[{tag}] 고르면 답장칸에 포커스')
        pg.get_by_role('button', name='답장 보내기').click()
        check('적어 주세요' in th.locator('.fa-msg').inner_text(), f'[{tag}] 빈 답장 막음')
        pg.fill('#fa-reply', '확인했어요. 10월부터 청년 지원이 시작돼서 다음 동기화 때 고칠게요.')
        pg.get_by_role('button', name='답장 보내기').click()
        pg.wait_for_function('document.querySelector(".fa-tab").innerText.replace("\\n","") === "답 필요0"')
        check(pg.locator('.fa-empty').first.inner_text().startswith('답할 의견이 없어요'), f'[{tag}] 답하면 답 필요 목록에서 빠짐')
        pg.get_by_role('button', name=re.compile('^진행 중')).click()
        pg.locator('.fa-item', has_text='교통비').first.click() if pg.locator('.fa-item', has_text='교통비').count() else pg.locator('.fa-item').first.click()
        th = pg.locator('.fa-thread')
        check('운영팀' in th.locator('.fa-bubble.staff').last.inner_text() and '10월부터' in th.inner_text(), f'[{tag}] 보낸 답장이 대화에 보임')
        check(th.locator('select').input_value() == 'seen', f'[{tag}] 답하면 확인함 상태')
        th.locator('select').select_option('done')
        pg.wait_for_function('document.querySelectorAll(".fa-tab")[2].innerText.replace("\\n","") === "완료2"')
        check(True, f'[{tag}] 완료로 바꾸면 완료 탭으로')
        pg.locator('.fa-bar select').select_option('chief')
        pg.get_by_role('button', name=re.compile('^전체')).click()
        pg.wait_for_function('[...document.querySelectorAll(".fa-item")].every(x => x.innerText.indexOf("이장") >= 0)')
        check(pg.locator('.fa-item').count() == 2, f'[{tag}] 창구로 거르기(이장 2)')
        check(pg.evaluate('document.documentElement.scrollWidth <= innerWidth'), f'[{tag}] 운영팀 화면 가로 넘침 없음')
        pg.locator('.fa-item').first.click()
        pg.screenshot(path=str(HERE / f'shot_admin_{tag}.png'), full_page=True)
        pg.get_by_role('button', name='로그아웃').click()
        pg.wait_for_selector('.fa-login')
        check(True, f'[{tag}] 로그아웃')
        pg.close()

        pg = b.new_page(viewport={'width': w, 'height': h})
        pg.goto(admin_url + '?missing=1')
        pg.fill('#fa-email', 'staff@eum.test'); pg.fill('#fa-pw', 'test1234'); pg.get_by_role('button', name='로그인').click()
        pg.wait_for_function('document.querySelector(".fa-msg") && document.querySelector(".fa-msg").innerText.indexOf("07") >= 0')
        check(True, f'[{tag}] 07 적용 전이면 안내')
        pg.close()
    b.close()
print('모두 통과' if not fails else f'실패 {len(fails)}건'); sys.exit(1 if fails else 0)
