const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {setup}=require('./economy_test.cjs');
const A='00000000-0000-0000-0000-000000000201',B='00000000-0000-0000-0000-000000000202';
(async()=>{const {db,user,rpc}=await setup();let n=0;const check=(x,label)=>{assert(x,label);n++;console.log('PASS '+label);};
const file=fs.readFileSync(path.join(__dirname,'../10_achievements.sql'),'utf8');
const achievement=(id,action='state',title=null)=>db.transaction(async t=>{await t.exec('set local role authenticated');await t.query("select set_config('request.jwt.claim.sub',$1,true)",[id]);return (await t.query('select sw_achievements($1,$2) d',[action,title])).rows[0].d;});
try{await user(A);await user(B);await rpc(A);await rpc(B);await db.exec(file);
 let a=await achievement(A);check(a.earned.length===0,'new user starts with zero achievements');
 await assert.rejects(()=>achievement(A,'equip','big-catch'),/title_locked/);check(true,'locked title cannot equip');
 await db.query("insert into sw_items(owner_id,item_id,size_cm,source) values($1,'carp',85,'legacy')",[B]);check((await achievement(B)).earned.length===0,'legacy browser fish do not unlock achievements');
 const fish=(await db.query("insert into sw_items(owner_id,item_id,size_cm,source,water_id) values($1,'carp',85,'fishing','lake') returning id",[A])).rows[0].id;
 a=await achievement(A);check(a.earned.length===2&&a.progress.bestFishCm===85,'large catch unlocks both size milestones');
 await achievement(A,'equip','big-catch');check((await achievement(A)).equippedTitle==='big-catch','earned title persists');
 await achievement(A,'equip','master-angler');check((await achievement(A)).equippedTitle==='master-angler','only one title equips');
 const offer=(await rpc(A,'offer',{instanceId:fish,buyerId:B,price:100})).result.offerId;await rpc(B,'accept_offer',{offerId:offer});
 check((await achievement(B)).earned.length===0,'buying large fish does not grant catch achievement');
 check((await achievement(A)).earned.length===2,'original catcher keeps achievement after trade');
 await db.exec(file);check((await achievement(B)).earned.length===0,'migration rerun does not award buyer for traded fish');
 check((await achievement(A)).equippedTitle==='master-angler','migration rerun preserves equipped title');
 const addTrash=async()=> (await db.query("insert into sw_items(owner_id,item_id,source) values($1,'bottle','fishing') returning id",[A])).rows[0].id;
 const first=await addTrash();await assert.rejects(()=>rpc(A,'recycle',{instanceId:first,category:'paper'}),/wrong_recycle_bin/);
 check((await achievement(A)).progress.recycledCount===0,'wrong bin grants no recycling progress');
 const request=crypto.randomUUID();await rpc(A,'recycle',{instanceId:first,category:'plastic'},request);await rpc(A,'recycle',{instanceId:first,category:'plastic'},request);
 check((await achievement(A)).progress.recycledCount===1,'retry counts a recycled item exactly once');
 for(let i=1;i<10;i++)await rpc(A,'recycle',{instanceId:await addTrash(),category:'plastic'});
 a=await achievement(A);check(a.earned.some(e=>e.id==='recycling-starter')&&a.progress.recycledCount===10,'10 correct items unlock recycling title');
 for(let i=10;i<50;i++)await rpc(A,'recycle',{instanceId:await addTrash(),category:'plastic'});
 a=await achievement(A);check(a.earned.length===4&&a.progress.recycledCount===50,'50 correct items unlock guardian title');
 await db.exec(file);check((await achievement(A)).progress.recycledCount===50,'migration rerun does not duplicate progress');
 await achievement(A,'equip',null);check((await achievement(A)).equippedTitle===null,'title unequips');
 await db.transaction(async t=>{await t.exec('set local role authenticated');await t.query("select set_config('request.jwt.claim.sub',$1,true)",[B]);check((await t.query('select * from sw_user_achievements')).rows.length===0,'RLS hides other user achievements');});
 await assert.rejects(()=>db.transaction(async t=>{await t.exec('set local role authenticated');await t.query("select set_config('request.jwt.claim.sub',$1,true)",[B]);await t.query("insert into sw_user_achievements(user_id,achievement_id) values($1,'big-catch')",[B]);}),/permission denied/);check(true,'browser cannot grant itself an achievement');
 console.log('TOTAL '+n+' checks');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
